package cl.ey.desafio.api.user.exception;

public enum ErrorEnum {

	CREDENCIALES_INVALIDAS,
	USUARIO_INACTIVO,
	AUTHORIZATION_INVALIDO,
	SINTAXIS_TOKEN_INCORRECTA,
	TOKEN_EXPIRADO,
	TOKEN_NO_VALIDO,
	TOKEN_NO_PERTENECE,
	USUARIO_EXISTENTE,
	EMAIL_EXISTENTE,
	EMAIL_EXISTE_OTRO_USER
}
