package cl.ey.desafio.api.user.exception;

public enum ErrorEnum {

	USUARIO_NAME_VACIO,
	USUARIO_NO_SE_PUEDE_CREAR,
	USUARIO_NO_SE_PUEDE_ACTUALIZAR,
	USUARIO_INACTIVO,
	USUARIO_NO_VALIDADO,
	CORREO_YA_REGISTRADO,
	CORREO_NO_CUMPLE_FORMATO,
	PROBLEMA_DE_CREDENCIALES,
	SINTAXIS_TOKEN_INCORRECTA,	
	CREDENCIALES_INVALIDAS,
	TOKEN_EXPIRADO,
	TOKEN_NO_VALIDO
	
}
